// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF9aDsHuJ3RGeO2F_LpBzkc_RDb8MCgNc',
    appId: '1:585488217722:web:a6295207e4c6494095adc3',
    messagingSenderId: '585488217722',
    projectId: 'ecommerceapp-e655b',
    authDomain: 'ecommerceapp-e655b.firebaseapp.com',
    storageBucket: 'ecommerceapp-e655b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASfq93fD-4Y-WJ3T3shbTNb0SAJT49vKY',
    appId: '1:585488217722:android:a6d2fccd344afbe595adc3',
    messagingSenderId: '585488217722',
    projectId: 'ecommerceapp-e655b',
    storageBucket: 'ecommerceapp-e655b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhGqNZ-572mkNe6nxUvnVgZ4N8j1WjsmQ',
    appId: '1:585488217722:ios:d4f0db3a35daaff695adc3',
    messagingSenderId: '585488217722',
    projectId: 'ecommerceapp-e655b',
    storageBucket: 'ecommerceapp-e655b.appspot.com',
    androidClientId: '585488217722-nl1k68hertll6qevs8c6glpqadi053m3.apps.googleusercontent.com',
    iosClientId: '585488217722-9nsip2r8m3sio90ijjvhh9vam5ujomt8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomerenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhGqNZ-572mkNe6nxUvnVgZ4N8j1WjsmQ',
    appId: '1:585488217722:ios:d4f0db3a35daaff695adc3',
    messagingSenderId: '585488217722',
    projectId: 'ecommerceapp-e655b',
    storageBucket: 'ecommerceapp-e655b.appspot.com',
    androidClientId: '585488217722-nl1k68hertll6qevs8c6glpqadi053m3.apps.googleusercontent.com',
    iosClientId: '585488217722-9nsip2r8m3sio90ijjvhh9vam5ujomt8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomerenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF9aDsHuJ3RGeO2F_LpBzkc_RDb8MCgNc',
    appId: '1:585488217722:web:d61e92179065044a95adc3',
    messagingSenderId: '585488217722',
    projectId: 'ecommerceapp-e655b',
    authDomain: 'ecommerceapp-e655b.firebaseapp.com',
    storageBucket: 'ecommerceapp-e655b.appspot.com',
  );

}